### ISSUE TITLE
some css and background gradient

### ISSUE THREAD

**Issue by ishanchaskar** [Novus-Neurons/talebuddy#9]
i would like to do some css changes to this repo of your can u please and assign this to me @Novus-Neurons

**Comment by gamedevCloudy** [comment]
> i would like to do some css changes to this repo of your can u please and assign this to me @Novus-Neurons

Please Go ahead.

**Comment by MohitSolunke** [comment]
Yes Continue

**Comment by GauraviVeling** [comment]
Hello. Please can you assign this issue to me . I would like contributing to the issue.

**Comment by MohitSolunke** [comment]
Just go on that repo and add one story in Talebuddy Repo
